# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Pull Template

on:
  workflow_call:
    inputs:
       ENVIRONMENT:
        required: true
        type: string
    secrets:
      USER_ID:
        required: true
      USER_PASS:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: node './setup.js'
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PASS: ${{ secrets.USER_PASS }}
          HOST: ${{ vars.HOST }}
      - run: node './main.js'
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PASS: ${{ secrets.USER_PASS }}
          HOST: ${{ vars.HOST }}
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ inputs.ENVIRONMENT }} # The branch name where you want to push the assets
          FOLDER: StaticCodeAnalysis # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Get Code: ({sha}) ${{inputs.ENVIRONMENT}} ${{github.event.issue.number}}" # The commit message
      - name: Close Issue
        run: gh issue close --comment "Code pull completed, auto-closing issue" "${{github.event.issue.number}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
