# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SN Pull Code

on:
  issues: 
    types: [ labeled ]

jobs:

#   it-pull:
#     runs-on: ubuntu-latest
#     environment: IT

#   hr-pull:
#     runs-on: ubuntu-latest
#     environment: HR

#   lab-pull:
#     runs-on: ubuntu-latest
#     environment: Lab

#   idc-pull:
#     runs-on: ubuntu-latest
#     environment: IDC

  dev-pull:
    if: ${{ github.event.label.name == 'DevInstance' }}
    runs-on: ubuntu-latest
    environment: DevInstance
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/sn-pull.yml@main
        with:
          env-name: DevInstance

